# Generated by Django 4.1.7 on 2023-03-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anish', '0002_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='pwd',
            new_name='pass1',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='pwd2',
            new_name='pass2',
        ),
    ]
