# Generated by Django 4.1.7 on 2023-03-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anish', '0003_rename_pwd_register_pass1_rename_pwd2_register_pass2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
