# Generated by Django 4.1.7 on 2023-03-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anish', '0004_alter_register_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=122),
        ),
    ]
